#Docker compose version
version: '3.7'

#Services to be powered up
services:
 
  #############################################
  ############# Servicio de MONGO #############
  #############################################
  mongodb:
    # Imagen de MongoDB a utilizar, junto con la última versión estable.
    image: "mongo:5.0.5"
    container_name: mongodb
    # Reinicia el servicio automáticamente.
    restart: always
    environment:
      - TZ=Europe/Madrid
    expose:
      - '27017'
    # Se mapean los puertos locales al servidor host.
    ports:
      - '27017:27017'
    # Se indica que tenemos un volumen para la base de datos. Con el objetivo, 
    #de persistir la información si paramos el contenedor.
    volumes:
      - mongodbvol:/data/db
      - ./mongo/backup:/data/backup
    # Indicamos que el contenedor se encuentra en una red, para que esté visible 
    #con el resto de contenedores.
    networks:
       - red-apps
  #############################################

#Adaptador de red comun
networks:
  red-apps:
    driver: bridge

# Definimos los volumenes de persistencia
volumes:
  mongodbvol: